apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: mykiwi/sfdemo:v4
        ports:
        - containerPort: 80
        env:
        - name: REDIS_URL
          value: redis://redis-svc
        # value: redis-svc.default.svc.cluster.local
        - name: DATABASE_URL
          value: mysql://root:@mysql-svc:3306/db
        # value: mysql-svc.default.svc.cluster.local
